"""initial schema

Revision ID: 4872d87fd5b0
Revises: 
Create Date: 2026-08-20 01:13:36.673191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4872d87fd5b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('actif', sa.SmallInteger(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('succes', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tribes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('langue', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('clans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tribe_id', sa.BigInteger(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tribe_id'], ['tribes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('sexe', sa.Enum('M', 'F', 'AUTRE'), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MODERATEUR', 'UTILISATEUR'), nullable=False),
    sa.Column('photo_profil', sa.String(length=255), nullable=True),
    sa.Column('biographie', sa.Text(), nullable=True),
    sa.Column('village_origine', sa.String(length=150), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('departement', sa.String(length=100), nullable=True),
    sa.Column('langue', sa.String(length=100), nullable=True),
    sa.Column('profession', sa.String(length=150), nullable=True),
    sa.Column('tribe_id', sa.BigInteger(), nullable=True),
    sa.Column('clan_id', sa.BigInteger(), nullable=True),
    sa.Column('email_verifie', sa.SmallInteger(), nullable=False),
    sa.Column('token_verification', sa.String(length=255), nullable=True),
    sa.Column('statut', sa.Enum('ACTIF', 'SUSPENDU', 'SUPPRIME'), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tribe_id'], ['tribes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ai_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('provider_id', sa.BigInteger(), nullable=True),
    sa.Column('type_requete', sa.Enum('GENEALOGIE', 'HISTOIRE', 'CULTURE', 'RECHERCHE_NATURELLE', 'CHATBOT'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('reponse', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('SUCCES', 'ECHEC'), nullable=False),
    sa.Column('duree_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('families',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('visibilite', sa.Enum('PRIVE', 'PARTAGE', 'PUBLIC'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_shares',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('permission', sa.Enum('LECTURE', 'EDITION'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id')
    )
    op.create_table('persons',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.BigInteger(), nullable=True),
    sa.Column('linked_user_id', sa.BigInteger(), nullable=True),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('prenom', sa.String(length=150), nullable=True),
    sa.Column('sexe', sa.Enum('M', 'F', 'INCONNU'), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('date_deces', sa.Date(), nullable=True),
    sa.Column('vivant', sa.SmallInteger(), nullable=False),
    sa.Column('village_id', sa.BigInteger(), nullable=True),
    sa.Column('tribe_id', sa.BigInteger(), nullable=True),
    sa.Column('clan_id', sa.BigInteger(), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tribe_id'], ['tribes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('related_person_id', sa.BigInteger(), nullable=False),
    sa.Column('type_relation', sa.Enum('PERE', 'MERE', 'CONJOINT', 'ENFANT', 'FRERE_SOEUR', 'GRAND_PARENT'), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'related_person_id', 'type_relation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationships')
    op.drop_table('persons')
    op.drop_table('family_shares')
    op.drop_table('refresh_tokens')
    op.drop_table('families')
    op.drop_table('ai_logs')
    op.drop_table('users')
    op.drop_table('clans')
    op.drop_table('tribes')
    op.drop_table('login_attempts')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
